### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by dnish** [dferber90/meteor-prerender#10]
Hey,
I'm just using your package but it isn't working for me. If I call my url with the escaped fragment, my Prerender server logs the call, but I get redirected to my root url without the escaped fragment. It is possible that it collides with <code>force-ssl</code>?

**Comment by dferber90** [comment]
Yeah that could be the case, haven't used it with `force-ssl`. I'm not sure though. The code in this package is minimal and you could copy it to your app and modify accordingly.

**Comment by dferber90** [comment]
@dnish FYI: I vaguely remember the `prerender-node` module used by this package always assuming a plain HTTP connection. I think this was resolved in the meantime. I also just released a new version. It might work now.
