### ISSUE TITLE
Possibility for whitelisting,blacklisting, set url dynamically,...

### ISSUE THREAD

**Issue by tcastelli** [dferber90/meteor-prerender#14]
Hello, could it be possible to add an export of the variable prerenderio?, otherwise I'm not sure on how are we supposed to add additional configurations for the nodejs package.

**Comment by dferber90** [comment]
This package isn't doing much. It's more of a reference on how to set everything up yourself.

With Meteor 1.3 (which will be released soon), it's trivial to use an npm package in the app. Until then, your best option is to download this package's source code, put it in the `packages` folder and modify it according to your needs :)

**Comment by dferber90** [comment]
Closing this, let me know in case anything else comes up.
