### ISSUE TITLE
blacklisted not working?

### ISSUE THREAD

**Issue by jsbranco** [dferber90/meteor-prerender#17]
Hi,

I attempted to add the following to my client-side :+1: 
    prerenderio.blacklisted('/result');

so that it stops caching my urls that contain www.example.com**/result**/test

However, I see in Prerender.io is still caching these links?

If I try to add the prerenderio to the server side it says that prerenderio is undefined.

**Comment by dferber90** [comment]
This package doesn't support what you're trying to do. This package doesn't export `prerenderio` itself. You can't change anything except for the `serviceUrl` and `token`. If you want to do more advanced stuff, use `prerender-node` directly. You can use this package as reference of how to set everything up yourself.

---

> I attempted to add the following to my client-side 
> prerenderio.blacklisted('/result');

All configuration for `prerender-node` would have to happen on the server, but again: this is not supported by this plugin.
