### ISSUE TITLE
Prerender not working on my app

### ISSUE THREAD

**Issue by kenshinman** [dferber90/meteor-prerender#20]
Hi, I have deployed my app with mupx on digital ocean, and I have followed the instructions on your README.MD but it appears that prerender.io is not seeing my app here is my setup

**settings.js**

```
{
    "public": {
        "ga": {
            "id": "UA-XXXXXXXX-1"
        },
        "PrerenderIO": {
            "serviceUrl": "http://service.prerender.io/",
            "token": "wi7Dqa...................qTGmT"
          }
    }
}
```

I have installed my token and your package. how do I know if this is working? i have also tried installing the prerender server locally but i have issues with this too. 

When I go to prerender i still see the prompt which says i should install my token on my site.

I also submitted my website's sitemap to prerender.io which means it has cached my pages (manually).

With all these, I'm not sure prerender is working on my app

**Comment by dferber90** [comment]
Did you start your application with `meteor --settings settings.json`?

I haven't used this package myself for quite some time. Maybe something else broke. Sorry, I can't really help you there.

**Comment by isAlmogK** [comment]
I had the same issue not sure it's picking up the settings.json file I would suggest just using   "env": {
 option

**Comment by dferber90** [comment]
@kenshinman You put the `PrerenderIO` settings under `public`, but it should be at the top-level :) 

Please close the issue if that fixes your problem ☺️

**Comment by dferber90** [comment]
``` json
{
  "public": {
    "ga": {
      "id": "UA-XXXXXXXX-1"
    }
  },
  "PrerenderIO": {
    "serviceUrl": "http://service.prerender.io/",
    "token": "wi7Dqa...................qTGmT"
  }
}
```
