### ISSUE TITLE
Protocol option not supported 

### ISSUE THREAD

**Issue by isAlmogK** [dferber90/meteor-prerender#21]
Hi the http / https protocol is not supported, it is supported in the node package version. You need this if your site / app is using https. Any plans to add this?

**Comment by dferber90** [comment]
No plans to add it. Will accept a PR though I think. As stated in other issues, this package is to be thought of more as a how-to. Anything that goes beyond basic configuration should rather be done by using the node package directly.

**Comment by isAlmogK** [comment]
Yea I would agree but I'm on very old meteor version and don't plan to update the app right now. Let me see about doing a PR

**Comment by isAlmogK** [comment]
Just created a pull request once, can you let me know once it's updated on atmosphere so I can update the package - https://github.com/dferber90/meteor-prerender/pull/22

**Comment by isAlmogK** [comment]
Did you update the package on meteor astomosper not seeing the update I'm on version 
dferber:prerender 2.2.0_2  Node wrapper for prerender
