### ISSUE TITLE
Error: Cannot read property 'access-control-allow-origin' of null

### ISSUE THREAD

**Issue by jamiedumont** [dferber90/meteor-prerender#24]
Hey,

Since about November, I've been seeing issues with using `mdg:seo` on Galaxy, getting the same error as seen [here](https://github.com/meteor/galaxy-seo-package/issues/5). I had to stop using the package because it caused rolling container crashes.

I assumed that it may have been an issue between Galaxy and Prerender, but when using your package earlier, I can into the same issue on my localhost.

The person that raised the issue over on `mdg:seo` speculated that it may be an interaction with the `meteor hacks:inject-data` package?

What would you say is the best way to resolve this issue, or use the NPM version of `prerender-node` directly? (I'm running Meteor 1.3+)

Cheers! Jamie.

**Comment by jamiedumont** [comment]
I can confirm that the issue lies with the `meteorhacks:inject-data` package being used by `kadirahq:flow-router-ssr` in Meteor versions 1.4.2+. There are alternative packages that have been updated since Kadira's abandonment of their packages (`staringatlights:inject-data` for example). Replacing FlowRouters dependency on `inject-data` with this alternative package appears to have worked for me.

I'm now using `staringatlights:inject-data`, `staringatlights:fast-render` and `bensventures:flow-router-ssr` and all is working well.

Leaving this here, and open, so that others who have run into this issue can see my solution.

**Comment by dferber90** [comment]
We close it in that case, they will still be able to see it :)
