### ISSUE TITLE
host issue

### ISSUE THREAD

**Issue by selaias** [dferber90/meteor-prerender#25]
Hi, 

for a reason I haven't figured out why the host is set as px 'example' while it should be 'example.com', so all attempts to prerender.io calls miss.  
I have downloaded a local copy and added prerenderio.set('host', host); with host being a value from the settings file.

Anyone has faced the same issue? It would be nice to add it as optional also in the package.

Thanks

**Comment by dferber90** [comment]
@selaias I do not understand your question unfortunately.

We are not setting the host at all as far as I remember. With newer versions of Meteor this package is quite useless. You  can just require `prerenderio` yourself. Maybe you wanted to open that issue in the official [prerenderio repository](https://github.com/prerender/prerender)? This package is only for the Meteor integration (which you only need with old versions that don't support npm modules out of the box).

**Comment by dferber90** [comment]
Feel free to reopen in case there is an issue I'm not seeing.

**Comment by selaias** [comment]
@dferber90 obviously I'm on an older Meteor version (prior 1.3) that's why I'm using your package.

Apparently there is an issue on the npm package also [https://github.com/prerender/prerender-node/issues/87](url)

and there is an option (not documented) about setting the host 

[https://github.com/prerender/prerender-node/blob/master/index.js#L251](url)
