### ISSUE TITLE
Brings in Blaze & jQuery to client 

### ISSUE THREAD

**Issue by stolinski** [dferber90/meteor-prerender#26]
Everything is working fine, but this package is relying on Templating that is bringing it in client side and bringing Blaze & jQuery along with it. :(

**Comment by dferber90** [comment]
From the README:

> This package is a reference on how to enable Prerender in pre-1.3 Meteor applications. If you need anything more sophisticated, create an inlined package in your project. It's just a few lines of code.
> 
> Meteor 1.3 supports inclusion of npm modules out of the box. If you use Meteor 1.3, use the `prerender-node` npm module directly. You don't need this package at all in this case.

I assume most pre-Meteor-1.3-applications will use `jQuery` and `Blaze`. All others can depend on `prerender-node` directly and use this package as a reference on how to integrate it on their own.

I'm closing this for now. Feel free to keep commenting in case you have a specific use-case not solved by what is stated above. I'll reopen when necessary.

**Comment by stolinski** [comment]
Understood.  I only arrived here because of the mdg:seo package which is the recommended way of enabling Prereneder on Galaxy regardless of Meteor version. No worries on the part of this package, just wondering why this is the recommended solution for Galaxy.
