### ISSUE TITLE
google boot issue

### ISSUE THREAD

**Issue by csKangGdcomm** [dferber90/meteor-prerender#28]
Hello,

I got an email from prerender and it said that I have to update my prerneder middleware version to support google boot.

I am using this repository so I am asking that what should I do for the email?

Thank you!! below is the email from prerender.

---

Hi there,

Please upgrade your Prerender.io middleware to the latest version or manually modify it to check for Googlebot by their user agent directly.

This is for your Prerender.io account under the email address of support@gdcomm.io.

Google is moving away from crawling _escaped_fragment_ URLs and some users have reported this causing issues with their SEO.

You can find information on Google's change and how to upgrade or add Googlebot's user agent to your middleware here:

https://prerender.io/documentation/google-support

I'll check your account again soon and I'll follow up with you if I don't see prerendered pages being returned to Googlebot directly.

Please respond to this email if you have any questions.

Best,

Todd Hooper
Founder, Lead Engineer

**Comment by dferber90** [comment]
I have not used Meteor or Prerender in a very long time, so I can't advise on how to proceed here.

**Comment by glasser** [comment]
Hi @dferber90! Thanks for the work you did on this package in the past. We're going to update `mdg:seo` (which currently is just an empty package depending on yours) to contain the contents of your (MIT-licensed) package, and then update it to the newer version as advised by Prerender.

**Comment by dferber90** [comment]
Thanks for chiming in @glasser! I'll update the README to state that this package is unmaintained and to use [`mdg:seo`](https://atmospherejs.com/mdg/seo) instead.
